settings:
  style: "seaborn-v0_8"
  context: "notebook"

pandas:
  max_rows: 60
  max_columns: 100

paths:
  plot_dir: "plots"
  read_file: "data/musteriyorumlari.xlsx"

models:
  sentiment: "savasy/bert-base-turkish-sentiment-cased"
   

